In [87]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [88]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [89]:
df

,text,category
0,Meditation and yoga can improve mental health,Health
1,"Fruits, whole grains and vegetables helps control blood pressure",Health
2,These are the latest fashion trends for this week,Fashion
3,Vibrant color jeans for male are becoming a trend,Fashion
4,The concert starts at 7 PM tonight,Event
5,Navaratri dandiya program at Expo center in Mumbai this october,Event
6,Exciting vacation destinations for your next trip,Travel
7,Maldives and Srilanka are gaining popularity in terms of low budget vacation places,Travel


In [113]:
df.text,df.text[0]

(0                                          Meditation and yoga can improve mental health
 1                       Fruits, whole grains and vegetables helps control blood pressure
 2                                      These are the latest fashion trends for this week
 3                                      Vibrant color jeans for male are becoming a trend
 4                                                     The concert starts at 7 PM tonight
 5                        Navaratri dandiya program at Expo center in Mumbai this october
 6                                      Exciting vacation destinations for your next trip
 7    Maldives and Srilanka are gaining popularity in terms of low budget vacation places
 Name: text, dtype: str,
 'Meditation and yoga can improve mental health')

### Creating Embedding on sample dataset to check how sent trans and faiss working

In [91]:
from sentence_transformers import SentenceTransformer
dir(SentenceTransformer)

['T_destination',
 '__abstractmethods__',
 '__add__',
 '__annotate_func__',
 '__annotations__',
 '__annotations_cache__',
 '__call__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__slots__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_apply',
 '_call_impl',
 '_can_flatten_inputs',
 '_compiled_call_impl',
 '_create_model_card',
 '_default_prompts',
 '_eval_during_training',
 '_first_module',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_item_by_idx',
 '_get_model

In [92]:
df.text[:]

0                                          Meditation and yoga can improve mental health
1                       Fruits, whole grains and vegetables helps control blood pressure
2                                      These are the latest fashion trends for this week
3                                      Vibrant color jeans for male are becoming a trend
4                                                     The concert starts at 7 PM tonight
5                        Navaratri dandiya program at Expo center in Mumbai this october
6                                      Exciting vacation destinations for your next trip
7    Maldives and Srilanka are gaining popularity in terms of low budget vacation places
Name: text, dtype: str

In [93]:
encoder = SentenceTransformer('all-MiniLM-L6-v2')


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1610.99it/s]


In [94]:
encoder,dir(encoder),type(encoder)

(SentenceTransformer(
   (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
   (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
   (2): Normalize({})
 ),
 ['T_destination',
  '__abstractmethods__',
  '__add__',
  '__annotate_func__',
  '__annotations__',
  '__annotations_cache__',
  '__call__',
  '__class__',
  '__delattr__',
  '__delitem__',
  '__dict__',
  '__dir__',
  '__doc__',
  '__eq__',
  '__firstlineno__',
  '__format__',
  '__ge__',
  '__getattr__',
  '__getattribute__',
  '__getitem__',
  '__getstate__',
  '__gt__',
  '__hash__',
  '__iadd__',
  '__imul__',
  '__init__',
  '__init_subclass__',
  '__iter__',
  '__le__',
  '__len__',
  '__lt__',
  '__module__',
  '__mul__',
  '__ne__',
  '__new__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__rmul__',
  '

In [95]:
type(df.text)


pandas.Series

In [96]:
import numpy as np
sentences = np.array(df.text)
sentences

array(['Meditation and yoga can improve mental health',
       'Fruits, whole grains and vegetables helps control blood pressure',
       'These are the latest fashion trends for this week',
       'Vibrant color jeans for male are becoming a trend',
       'The concert starts at 7 PM tonight',
       'Navaratri dandiya program at Expo center in Mumbai this october',
       'Exciting vacation destinations for your next trip',
       'Maldives and Srilanka are gaining popularity in terms of low budget vacation places'],
      dtype=object)

In [97]:
vectors = encoder.encode(sentences)

In [98]:
vectors

array([[ 0.06386317,  0.02910282,  0.00976354, ...,  0.0102302 ,
        -0.0223121 , -0.00268405],
       [-0.05709033,  0.09636035,  0.00199013, ...,  0.06168112,
        -0.02260813,  0.03472494],
       [-0.08079232, -0.03503961,  0.03106477, ..., -0.16189392,
         0.01315195,  0.05600098],
       ...,
       [-0.03807864,  0.00503377, -0.06084297, ..., -0.03014938,
        -0.05972223,  0.04858849],
       [ 0.09595465, -0.01580386,  0.00767664, ..., -0.06537458,
        -0.07525399, -0.04042162],
       [ 0.150499  , -0.01106242, -0.02882517, ..., -0.07340208,
        -0.05694249,  0.02461096]], shape=(8, 384), dtype=float32)

In [99]:
vectors.shape,type(vectors),np.ndim(vectors),vectors.size

((8, 384), numpy.ndarray, 2, 3072)

In [100]:
vector_dim = vectors.shape[1]
vector_dim,type(vectors.shape)


(384, tuple)

In [101]:
type(vectors[0]),vectors[0][0],vectors[0],df['text'],df['text'][0]

(numpy.ndarray,
 np.float32(0.063863166),
 array([ 6.38631657e-02,  2.91028246e-02,  9.76353604e-03,  1.35569312e-02,
        -1.99523382e-02,  1.10954329e-01,  3.22393961e-02, -8.65306258e-02,
         4.64022011e-02, -1.46870930e-02,  6.07167594e-02,  8.92161876e-02,
        -4.74637374e-02, -5.22289574e-02,  1.66329250e-01,  7.64086284e-03,
        -4.48196894e-03,  7.96060711e-02, -5.03407493e-02,  2.31804196e-02,
        -7.67793730e-02,  2.80923136e-02,  4.48424593e-02,  4.74730209e-02,
        -2.75150500e-02,  5.87531216e-02, -3.19126137e-02, -9.40763801e-02,
         5.06361611e-02,  5.76460361e-02,  8.29015523e-02,  5.96740842e-02,
        -8.77050404e-03,  4.33064299e-03, -2.87840627e-02,  5.11236042e-02,
        -3.96298170e-02,  3.27941254e-02,  2.16200165e-02, -6.95767924e-02,
        -7.08739460e-02,  2.72168107e-02,  7.11242706e-02,  1.66329145e-02,
        -2.57110409e-02, -1.21312141e-02, -6.40070415e-04, -5.40267490e-03,
         7.02305660e-02, -1.30492583e-01, -8.3

In [102]:
# The sentences vs vectors
df['text'][0],vectors[0]

('Meditation and yoga can improve mental health',
 array([ 6.38631657e-02,  2.91028246e-02,  9.76353604e-03,  1.35569312e-02,
        -1.99523382e-02,  1.10954329e-01,  3.22393961e-02, -8.65306258e-02,
         4.64022011e-02, -1.46870930e-02,  6.07167594e-02,  8.92161876e-02,
        -4.74637374e-02, -5.22289574e-02,  1.66329250e-01,  7.64086284e-03,
        -4.48196894e-03,  7.96060711e-02, -5.03407493e-02,  2.31804196e-02,
        -7.67793730e-02,  2.80923136e-02,  4.48424593e-02,  4.74730209e-02,
        -2.75150500e-02,  5.87531216e-02, -3.19126137e-02, -9.40763801e-02,
         5.06361611e-02,  5.76460361e-02,  8.29015523e-02,  5.96740842e-02,
        -8.77050404e-03,  4.33064299e-03, -2.87840627e-02,  5.11236042e-02,
        -3.96298170e-02,  3.27941254e-02,  2.16200165e-02, -6.95767924e-02,
        -7.08739460e-02,  2.72168107e-02,  7.11242706e-02,  1.66329145e-02,
        -2.57110409e-02, -1.21312141e-02, -6.40070415e-04, -5.40267490e-03,
         7.02305660e-02, -1.30492583e-

# Creating Faiss DB
[Faiss Python Docs](https://github.com/facebookresearch/faiss/wiki/Getting-started)

In [103]:
import faiss
dir(faiss)

['APPROX_TOPK_BUCKETS_B16_D2',
 'APPROX_TOPK_BUCKETS_B32_D2',
 'APPROX_TOPK_BUCKETS_B8_D2',
 'APPROX_TOPK_BUCKETS_B8_D3',
 'AdditiveCoarseQuantizer',
 'AdditiveQuantizer',
 'AlignedTableFloat32',
 'AlignedTableUint16',
 'AlignedTableUint8',
 'AlignedTable_to_array',
 'ArrayInvertedLists',
 'ArrayInvertedListsPanorama',
 'AutoTuneCriterion',
 'BinaryInvertedListScanner',
 'BitstringReader',
 'BitstringWriter',
 'BlockInvertedLists',
 'BufferList',
 'BufferedIOReader',
 'BufferedIOWriter',
 'ByteVector',
 'ByteVectorVector',
 'CMax_float_partition_fuzzy',
 'CMax_uint16_partition_fuzzy',
 'CMin_float_partition_fuzzy',
 'CMin_uint16_partition_fuzzy',
 'CappedInvertedLists',
 'CenteringTransform',
 'CharVector',
 'Cloner',
 'Clustering',
 'Clustering1D',
 'ClusteringInitMethod_AFK_MC2',
 'ClusteringInitMethod_KMEANS_PLUS_PLUS',
 'ClusteringInitMethod_RANDOM',
 'ClusteringInitialization',
 'ClusteringIterationStats',
 'ClusteringIterationStatsVector',
 'ClusteringParameters',
 'CodePacker',


In [104]:
index  = faiss.IndexFlatL2(vector_dim)   # build the index

type(index),dir(index)

(faiss.swigfaiss.IndexFlatL2,
 ['__class__',
  '__delattr__',
  '__dict__',
  '__dir__',
  '__doc__',
  '__eq__',
  '__firstlineno__',
  '__format__',
  '__ge__',
  '__getattribute__',
  '__getstate__',
  '__gt__',
  '__hash__',
  '__init__',
  '__init_subclass__',
  '__le__',
  '__lt__',
  '__module__',
  '__ne__',
  '__new__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__setattr__',
  '__setstate__',
  '__sizeof__',
  '__static_attributes__',
  '__str__',
  '__subclasshook__',
  '__swig_destroy__',
  '__weakref__',
  'add',
  'add_c',
  'add_ex',
  'add_sa_codes',
  'add_sa_codes_c',
  'add_with_ids',
  'add_with_ids_c',
  'add_with_ids_ex',
  'assign',
  'assign_c',
  'cached_l2norms',
  'check_compatible_for_merge',
  'clear_l2norms',
  'code_size',
  'codes',
  'compute_distance_subset',
  'compute_residual',
  'compute_residual_n',
  'd',
  'get_CodePacker',
  'get_FlatCodesDistanceComputer',
  'get_distance_computer',
  'get_xb',
  'is_trained',
  'merge_from',
  'metri

In [105]:
vectors.shape

(8, 384)

In [106]:
index.ntotal

0

In [107]:
index.add(vectors)

In [108]:
index,index.d

(<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001F1C8C61470> >,
 384)

In [109]:
search_query = 'I want to eat an apple'
search_vector = encoder.encode(search_query)
print(type(search_vector))
print(search_vector.shape)
print(search_vector)

<class 'numpy.ndarray'>
(384,)
[ 4.40554470e-02 -5.95291238e-03 -2.31272150e-02  3.66934650e-02
 -1.13278873e-01 -5.12051694e-02  2.86757983e-02 -6.91706613e-02
 -1.24565078e-04 -6.57106692e-04  5.69474287e-02 -1.04738854e-01
 -3.65293100e-02 -5.45392781e-02  4.07956541e-02 -3.69245298e-02
  5.62703237e-02  3.70213389e-02 -2.05877032e-02 -1.59778930e-02
  4.54150792e-03  5.56850471e-02 -1.47952680e-02 -1.79060344e-02
 -2.71085706e-02  2.89639402e-02  3.95559333e-02 -4.39598002e-02
 -7.00347200e-02 -1.06024556e-02  6.12058956e-03 -6.95443749e-02
  2.61060931e-02  3.95359956e-02 -5.23845851e-02 -3.96402031e-02
  9.18621719e-02 -1.17060170e-01  3.50064524e-02 -1.81230495e-03
  1.41393831e-02  5.50079495e-02  2.77019721e-02  2.91422084e-02
 -5.06300330e-02  1.48752937e-02 -4.46247421e-02  4.29594554e-02
  1.21011719e-01  5.34948409e-02 -4.36771251e-02 -4.66565154e-02
 -4.61726375e-02 -4.93075103e-02  6.49102926e-02  7.35958070e-02
  1.12522068e-02  1.41626298e-02  5.16053215e-02  4.4547304

In [110]:
import numpy as np

# 1. Reshape the vector to be 2D (1 row, 384 columns)
search_vector_2d = search_vector.reshape(1, -1)
print(search_vector_2d.shape)  # Output: (1, 384)

# 2. Unpack BOTH outputs from the search function
A = index.search(x=search_vector_2d, k=3)
print(A,type(A))

(1, 384)
(array([[1.2944537, 1.7636764, 1.8167323]], dtype=float32), array([[1, 0, 6]])) <class 'tuple'>


In [115]:
# error faiss requires 2d array or matrx to search
# topk_nearest_vectors_search_vector = index.search(x=search_vector,k=1)

import numpy as np

# 1. Reshape the vector to be 2D (1 row, 384 columns)
search_vector_2d = search_vector.reshape(1, -1)
print(search_vector_2d.shape)  # Output: (1, 384)

# 2. Unpack BOTH outputs from the search function
distances, indices = index.search(x=search_vector_2d, k=3)
print(type(distances),type(indices))


# 3. View your results
print("Nearest neighbor IDs:", indices)
# print(indices[0][0])
print("Squared L2 distances:", distances)

for i in indices[0]:
    print("Index:- ",i,"Corresponding text in datafram:- ",df.text[i])

(1, 384)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Nearest neighbor IDs: [[1 0 6]]
Squared L2 distances: [[1.2944537 1.7636764 1.8167323]]
Index:-  1 Corresponding text in datafram:-  Fruits, whole grains and vegetables helps control blood pressure
Index:-  0 Corresponding text in datafram:-  Meditation and yoga can improve mental health
Index:-  6 Corresponding text in datafram:-  Exciting vacation destinations for your next trip


In [117]:
search_query = "I want to buy a polo t-shirt"
# search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
search_vector = encoder.encode(search_query)
search_vector
search_vector_2d = search_vector.reshape(1, -1)
print(search_vector_2d.shape)  # Output: (1, 384)

# 2. Unpack BOTH outputs from the search function
distances, indices = index.search(x=search_vector_2d, k=3)
print(type(distances),type(indices))


# 3. View your results
print("Nearest neighbor IDs:", indices)
# print(indices[0][0])
print("Squared L2 distances:", distances)

for i in indices[0]:
    print("Index:- ",i,"Corresponding text in datafram:- ",df.text[i])


(1, 384)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Nearest neighbor IDs: [[3 2 6]]
Squared L2 distances: [[1.4139273 1.4256653 1.8171235]]
Index:-  3 Corresponding text in datafram:-  Vibrant color jeans for male are becoming a trend
Index:-  2 Corresponding text in datafram:-  These are the latest fashion trends for this week
Index:-  6 Corresponding text in datafram:-  Exciting vacation destinations for your next trip
